## Numpy Library in Pyhton

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

Numpy needs to be installed in a env, does not come by default.

In [ ]:

%pip install numpy # (magic command) Install numpy package in current environment
!pip install numpy # Install numpy package at shell level

Note: you may need to restart the kernel to use updated packages.


In [ ]:
## we need to import numpy before using it. np is the alias name

import numpy as np

## Creating numpy arrays using array() function
## create a 1D array
array1 = np.array([1, 2, 3, 4, 5])
print("1D array: ", array1)  # looks like list but it's not. We can pass list or tuple
print("Type is: ", type(array1))
print("Shape is: ", array1.shape)
## .shape gives the dimensions (structure) of Numpy array or Pandas DataFrame

1D array:  [1 2 3 4 5]
Type is:  <class 'numpy.ndarray'>
Shape is:  (5,)


In [ ]:
## Creating a 2D array

array2 = np.array((1, 2, 3, 4, 5))  # tuple passed
array2.reshape(1,5)

## output is same as 1D array but shape is different, we can see by [[two brackets]]
## New dimensions are 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [26]:
## We can create 2D array by passing list of lists or tuple of tuples also

array2D = np.array([[1, 2, 3, 4, 5, 6]])
print("2D array: \n", array2D)
print("Type is: ", type(array2D))
print("Shape is: ", array2D.shape)  # 1 row and 6

2D array: 
 [[1 2 3 4 5 6]]
Type is:  <class 'numpy.ndarray'>
Shape is:  (1, 6)


In [27]:
## with 2D array we can create multiple rows and columns

array2D_multi = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array with multiple rows and columns: \n", array2D_multi)
array2D_multi.shape  # 2 rows and 3 columns

2D array with multiple rows and columns: 
 [[1 2 3]
 [4 5 6]]


(2, 3)

In [32]:
## Creating arrays with in-built functions

print(np.arange(0, 10, 2))  # similar to range() function but returns numpy array
print(np.arange(0, 10, 2).reshape(5, 1))  # reshaping to 5 rows and 1 column
print(np.arange(0, 10, 2).reshape(5, 1).shape)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
(5, 1)


In [ ]:
## Create array of ones and zeros
ones_array = np.ones((3, 4))  # 3 rows and 4
print("Array of ones: \n", ones_array)

zero_array = np.zeros((3, 4))
print("Array of zeros: \n", zero_array)

## This is helpful in deep learning when we need to initialize weights with ones or zeros

Array of ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
## Creating an identity matrix
identity_matrix = np.eye(4)  # 4x4 identity matrix
print("Identity Matrix: \n", identity_matrix)

Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
## Some Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)
print("Total bytes consumed:", arr.nbytes)  # Output: 48 (may vary based on platform)
print("Transpose of the array:\n", arr.T)  # Transpose of the array

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [40]:
## Numpy vectorized operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

## Element wise Addition
print("Addition:", arr1 + arr2)

## Element wise Substraction
print("Substraction: ", arr1 - arr2)

## Element wise Multiplication
print("Multiplication: ", arr1 * arr2)

## Element wise Division
print("Division: ", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [42]:
## Universal Functions
## These also apply element wise

arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential fn
print(np.exp(arr))

## Natural log
print(np.log(arr))

## Trigonometric fn
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [51]:
## Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
## Accessing the elements

print(arr[0][0])
print(arr[1:])
print(arr[1:,2:])
print(arr[0:2,2:])
print(arr[::2])

1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
# Working/Slicing with 3-D Arrays (N-D arrays)

arr3D = np.array([
    [[1,2,3],[2,3,4],[3,4,5]],
    [[4,5,6],[5,6,7],[6,7,8]],
    [[7,8,9],[8,9,10],[9,10,11]]
    ])
print(arr3D.shape)
print(arr3D[:,:,:2]) #all blocks, all rows, first 2 columns
print(arr3D[:,::2]) #all blocks, alternate rows, all columns
print(arr3D[::2]) #aternate block, all rows and columns

(3, 3, 3)
[[[ 1  2]
  [ 2  3]
  [ 3  4]]

 [[ 4  5]
  [ 5  6]
  [ 6  7]]

 [[ 7  8]
  [ 8  9]
  [ 9 10]]]
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 9 10 11]]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [125]:
## Modify array elements

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
arr[0,0] = 100
print("Modified\n", arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Modified
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
# Replacing all row elements
arr[1:] = 120 #replace 2nd and 3rd row elements
print(arr)

[[100   2   3   4]
 [120 120 120 120]
 [120 120 120 120]]


In [128]:
# Replace column elements
arr[1,1:3] = 150
print(arr)

[[100   2   3   4]
 [120 150 150 120]
 [120 120 120 120]]


In [2]:
## Statistical Concept -- Normalization
## Normalization is changing data to have mean = 0 and std deviation = 1
import numpy as np

data = np.array([1, 2, 3, 4, 5])

## Calculate mean and std deviation
data_mean = np.mean(data)
data_sd = np.std(data)

## Normalized data
norm_data = (data - data_mean)/data_sd
print(f"Normalized data \n {norm_data}")


Normalized data 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [3]:
## Logical Operations on nparrays (&,|)

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data<5]

array([1, 2, 3, 4])

In [5]:
data[(data>=5) & (data<=9)]

array([5, 6, 7, 8, 9])

### Other Learnings

1 In np.array() function we can create numpy arrays by passing: 
a lists/
b tuples/
c other numpy arrays/
d array.array objects/
e Scalar values
f Array like objects, such as:/
generators that yield numerical values/
Pandas series and DataFrames/
range()

2 Inconsistent shapes will give 1D array of Python objects, not N-d array.
eg np.array([[1, 2], [3]])
→ array([list([1, 2]), list([3])], dtype=object)

3 Generators can only be used once (one-pass-only)

4 In Python, particularly within the NumPy library, dtype (short for data type) refers to an object that describes the type of elements stored in a NumPy array. Understanding dtype is crucial for efficient data handling and numerical computations in Python, especially when working with large datasets.
It can be int, float, bool or even Python object.

5

There are two methods to convert df to np array:
a df.array(df)
b df.to_numpy()

df.to_numpy() is safer and respects Pandas internal data structures and chooses the most appropriate NumPy dtype. It has more predictable behavior with categorical data, datetime tyoes or extension dtypes.

np.array(df) is more generic NumPy conversion and tries to convert the entire DataFrame as an “array-like object.”

6

What is array.array in Python? | array module in Python
The array.array in Python is a module that provides an efficient way to store and manipulate homogeneous data.
It is compact, typed, memory-efficient array. compact, typed, memory-efficient array. Stores values in contiguous memory. Supports basic operations, But not vectorized math like NumPy.

The first argument ('i') is a type code, telling Python what data type the array will store.

They support List-like operations and methods.


In [18]:
## we create array using array module
import array

a = array.array('i', [1, 2, 3, 4])   # 'i' = signed integer
print(a)

array('i', [1, 2, 3, 4])


What are linters?

A linter is a static code analysis tool that examines source code to identify programming errors, stylistic issues, and potential bugs. It helps improve code quality and consistency by automatically checking the code against a set of predefined rules before the program runs

7 Useful attrybutes of numpy arrays in DataScience

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3) Used everywhere in ML: reshaping, batching, model inputs.
print("Number of dimensions:", arr.ndim)  # Output: 2 (Useful in deep learning. Images are 3D arrays and videos are 4D in numpy)
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)
print("Total bytes consumed:", arr.nbytes)  # Output: 48 (may vary based on platform)Used for estimating memory requirements.
print("Transpose of the array:\n", arr.T)  # Transpose of the array. Common in linear algebra & machine learning.
arr.real and arr.imag  #For complex numbers, often used in signal processing.
arr.flat  #Returns a 1D iterator over the array elements. Useful when looping efficiently.
arr.strides  #Tells how many bytes to step to move to the next element in each dimension. More advanced but useful for performance tuning.